name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NODE_ENV: test

jobs:
  buildAndTest:
    name: CI Pipeline
    runs-on: ubuntu-latest
    container: node:12

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: "test"
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        # ports:
        #   - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Angular dependencies
        run: npm ci

      - name: Run Angular Tests
        run: npm run test:coverage

      - name: Install Express dependencies
        run: npm --prefix ./server ci

      - name: Run Migration
        run: npm --prefix ./server run migrate

      - name: Run Express Tests
        run: npm --prefix ./server run coverage

      - name: Run Linting
        run: npm --prefix ./server run lint 

  deploy:
    name: CD Pipeline
    runs-on: ubuntu-latest
    needs: buildAndTest

    steps:
      - uses: actions/checkout@v2
